/* This file contains function declarations and includes for elm327 specific code
* such as command generation

*
*Author: Josh McIntyre
*/

#include <iostream>

#include "serial.h"
#include "command.h"

/* This class abstracts away the details of generating ELM327 commands
* and processing responses generated by the chip
*/
class ElmDevice
{
	private:
		SerialConnection connection;

		void init_settings();
		
	public:
		ElmDevice();
		std::string get_data(Command::COMMAND cmd);
		

};


